#!/bin/bash
#PBS -l walltime=00:10:00
#PBS -l nodes=4:ppn=12
#PBS -N mp2
#PBS -j oe

# Move to your mp0 directory
cd /home/"netid"/MP2

module load mpi

rind=( 2302 4318 10078 )
cind=( 2300 4316 10076 )

iter=0
for gsize in 2304 4320 10080
do

	for cores in 12 24 36 48
	do

		echo "Running with n=${gsize} p=${cores}" >> out_mp2.txt

		# Run MP2
		mpirun -n $cores ./pjacobi $gsize 100 ${rind[$iter]} ${cind[$iter]} >> out_mp2.txt
	
	done
	iter=$iter+1

done

