TGT=RadioStation
DEPS= DiscJockey.java  SongInfo.java  SongIterator.java  SongOfThe70s.java  SongOfThe80s.java  SongOfThe90s.java

CC=javac

$(TGT).class: $(TGT).java $(DEPS)
	$(CC) $(TGT).java 

clean: 
	-$(RM) *.class

